[workspace]
default-members = ["aetheria"]
members = [
  "assets",
  "aetheria",
  "arbiter",
  "gltf",
  "hecs",
  "hecs/macros",
  "net",
  "vulkan"
]
resolver = "2"

[profile.release]
debug = true
