[package]
name = "assets"
version = "0.1.0"
edition = "2021"

[dependencies]
assets-macros = { path = "macros" }

bytemuck = "1.13"

[build-dependencies]
assets-build = { path = "build" }
walkdir = "2.3"
