CREATE TABLE IF NOT EXISTS items
(
  id INTEGER PRIMARY KEY NOT NULL UNIQUE,
  item INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  owner INTEGER NOT NULL,
  FOREIGN KEY (owner) REFERENCES characters (id)
);
